# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MsgSafe' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MsgSafe

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  # target 'MsgSafeTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

  pod 'TrustKit'
  
  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

  pod 'react-native-background-timer', :path => '../node_modules/react-native-background-timer'

end
